version: 2
jobs:
  dependencies:
    pre:
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
  build:
    docker:
      - image: circleci/node:8.9.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
  deployment:
    npm:
      tag: /v[0-9]+(\.[0-9]+)*/
          commands:
        - npm publish
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deployment:
          requires:
            - build
